### PR TITLE
Fixed an issue where `.queryWith("...").stream().map(r -> r).iterator()` caused an error.

### LINKED ISSUE #141: An error occurs in `.queryWith("...").stream().map(r -> r).iterator()`
When generating a `Stream` from a query, creating an `iterator` from a `Stream`, and iterating, an error occurs at the last `hasNext()`.

The following code will not cause an error,

```java
sqlAgent
    .queryWith("...")
    .stream()
    .iterator()
```

But, the following code will cause an error.

```java
sqlAgent
    .queryWith("...")
    .stream()
    .map(r -> r)
    .iterator()
```

### PR DESCRIPTION
**Pull request by ota-meshi**
Fixed #141

### CODE REVIEW

File: src/test/java/jp/co/future/uroborosql/Issue141Test.java [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+		int c = 0;
+		while (itr.hasNext()) {
+			itr.next();
+			c++;
+		}
+		assertThat(c, is(2));
+	}
+
+	@Test
+	public void testIssue() {
```
Comment (ota-meshi) [inline src/test/java/jp/co/future/uroborosql/Issue141Test.java]: This test case fails before fix.
